# Reading List {-}

Source: <a href="https://www.ascp.org/content/board-of-certification/get-credentialed#" target="_blank">MLT(ASCP) and MLS(ASCP) Certifications > Applicant Resources > Reading List</a>

ASCP makes it clear that their suggested reading/reference list for the Medical Laboratory Technician, MLT(ASCP), and the Medical Laboratory Scientist, MLS(ASCP), certification exams "is intended only as a partial reference source". The suggested reading/reference list below was last revised on ASCP's website January 2025

## **Journals** {-}
*   <a href="https://clsjournal.ascls.org/" target="_blank">Clinical Laboratory Science.</a> Published by American Society for Clinical Laboratory Science.
*   <a href="academic.oup.com/labmed" target="_blank">Laboratory Medicine.</a> Published by Oxford University Press.
*   <a href="https://www.mlo-online.com/" target="_blank">Medical Laboratory Observer.</a> Published by Endeavor Business Media, LLC.

## **Texts** {-}

### **Urinalysis & Body Fluids** {-}
*   Brunzel, N.A. (2022). Fundamentals of Urine and Body Fluid Analysis (5th ed.). St. Louis, MO: Elsevier.
*   Kjeldsberg, C. & Hussong, J. (2015). Kjeldsberg’s Body Fluid Analysis. Chicago, IL: ASCP Press.
*   Mundt, L.A. & Shanahan, K. (2016). Graff's Textbook of Urinalysis and Body Fluids (3rd ed.). Burlington, MA: Jones & Bartlett Learning.
*   Strasinger, S.K. & Di Lorenzo, M.S. (2021). Urinalysis and Body Fluids (7th ed.). Philadelphia: F.A. Davis Company.