# Further Readings {-}

Dababneh Y, Mousa OY. Serous Pancreatic Neoplasms. [Updated 2022 Oct 31]. In: StatPearls [Internet]. Treasure Island (FL): StatPearls Publishing; 2025 Jan-. Available from: https://www.ncbi.nlm.nih.gov/books/NBK557432/

Anwar A, Kasi A. Peritoneal Cancer. [Updated 2024 Apr 30]. In: StatPearls [Internet]. Treasure Island (FL): StatPearls Publishing; 2025 Jan-. Available from: https://www.ncbi.nlm.nih.gov/books/NBK562138/

Willner DA, Goyal A, Grigorova Y, et al. Pericardial Effusion. [Updated 2024 Jul 17]. In: StatPearls [Internet]. Treasure Island (FL): StatPearls Publishing; 2025 Jan-. Available from: https://www.ncbi.nlm.nih.gov/books/NBK431089/

Willner DA, Shams P, Grossman SA. Pericardiocentesis. [Updated 2025 Jan 19]. In: StatPearls [Internet]. Treasure Island (FL): StatPearls Publishing; 2025 Jan-. Available from: https://www.ncbi.nlm.nih.gov/books/NBK470347/

Volpe JK, Makaryus AN. Anatomy, Thorax, Heart and Pericardial Cavity. [Updated 2023 Jul 25]. In: StatPearls [Internet]. Treasure Island (FL): StatPearls Publishing; 2025 Jan-. Available from: https://www.ncbi.nlm.nih.gov/books/NBK482452/

Rehman I, Nassereddin A, Rehman A. Anatomy, Thorax, Pericardium. [Updated 2023 Jul 24]. In: StatPearls [Internet]. Treasure Island (FL): StatPearls Publishing; 2025 Jan-. Available from: https://www.ncbi.nlm.nih.gov/books/NBK482256/

Dababneh E, Siddique MS. Pericarditis. [Updated 2025 Jul 6]. In: StatPearls [Internet]. Treasure Island (FL): StatPearls Publishing; 2025 Jan-. Available from: https://www.ncbi.nlm.nih.gov/books/NBK431080/

Krishna R, Antoine MH, Alahmadi MH, et al. Pleural Effusion. [Updated 2024 Aug 31]. In: StatPearls [Internet]. Treasure Island (FL): StatPearls Publishing; 2025 Jan-. Available from: https://www.ncbi.nlm.nih.gov/books/NBK448189/

Agarwal A, Adeyinka A, Kondamudi NP. Pediatric Malignant Pleural Effusion. [Updated 2025 Feb 17]. In: StatPearls [Internet]. Treasure Island (FL): StatPearls Publishing; 2025 Jan-. Available from: https://www.ncbi.nlm.nih.gov/books/NBK507720/

Sharma S, Arora RD, Boster J. Malignant Pleural Effusion. [Updated 2024 Aug 12]. In: StatPearls [Internet]. Treasure Island (FL): StatPearls Publishing; 2025 Jan-. Available from: https://www.ncbi.nlm.nih.gov/books/NBK574541/

Shebl E, Paul M. Parapneumonic Pleural Effusions and Empyema Thoracis. [Updated 2023 Aug 7]. In: StatPearls [Internet]. Treasure Island (FL): StatPearls Publishing; 2025 Jan-. Available from: https://www.ncbi.nlm.nih.gov/books/NBK534297/

Wiederhold BD, Sharma S, O'Rourke MC. Thoracentesis. [Updated 2024 Oct 6]. In: StatPearls [Internet]. Treasure Island (FL): StatPearls Publishing; 2025 Jan-. Available from: https://www.ncbi.nlm.nih.gov/books/NBK441866/

D'Agostino HP, Edens MA. Physiology, Pleural Fluid. [Updated 2023 Aug 28]. In: StatPearls [Internet]. Treasure Island (FL): StatPearls Publishing; 2025 Jan-. Available from: https://www.ncbi.nlm.nih.gov/books/NBK513353/

Chiejina M, Kudaravalli P, Samant H, et al. Ascites (Nursing) [Updated 2023 Aug 8]. In: StatPearls [Internet]. Treasure Island (FL): StatPearls Publishing; 2025 Jan-. Available from: https://www.ncbi.nlm.nih.gov/books/NBK568749/

Farhana A, Lappin SL. Biochemistry, Lactate Dehydrogenase. [Updated 2023 May 1]. In: StatPearls [Internet]. Treasure Island (FL): StatPearls Publishing; 2025 Jan-. Available from: https://www.ncbi.nlm.nih.gov/books/NBK557536/

Sattar SBA, Nguyen AD, Sharma S, et al. Bacterial Pneumonia (Nursing) [Updated 2024 Feb 26]. In: StatPearls [Internet]. Treasure Island (FL): StatPearls Publishing; 2025 Jan-. Available from: https://www.ncbi.nlm.nih.gov/books/NBK568697/

